# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11381d45ddc4c05f2362bae6d366f950e3f59f3dbe22ef9b12c6942b3cab4aae17c93e68f3367dbaa37083db91881884af34dc1bdf53b4772d487006df3d5656

test:
  secret_key_base: 5211092cc48eb2f84ecf8190a618af17f4ea641372af789d89c6c1c92f22c402f758eee00948b507e6b27315f133cd8ef3e87f9270439882bea85ecee132b2be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
